# Generated by Django 6.0.1 on 2026-03-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('TRANSFER', 'Bank Transfer'), ('CREDIT', 'Credit (Pay Later)')], default='CASH', max_length=20),
        ),
    ]
