# Generated by Django 6.0.1 on 2026-03-05 09:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customer_customer_number'),
        ('orders', '0008_alter_orderpayment_payment_method'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='credit_approved_by',
            field=models.ForeignKey(blank=True, help_text='Manager who approved the credit sale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_credit_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='credit_due_date',
            field=models.DateField(blank=True, help_text='Due date for credit payment', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sale_type',
            field=models.CharField(choices=[('CASH', 'Cash Sale'), ('CREDIT', 'Credit Sale')], db_index=True, default='CASH', help_text='Whether this is a cash sale or credit sale', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Link to customer record (required for credit sales)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('TRANSFER', 'Bank Transfer'), ('CREDIT', 'Credit (Deprecated - Use order.sale_type)')], default='CASH', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['sale_type', 'payment_status'], name='orders_orde_sale_ty_5be9e4_idx'),
        ),
    ]
