# Generated by Django 6.0.1 on 2026-03-05 09:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customer_customer_number'),
        ('orders', '0009_order_credit_approved_by_order_credit_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_sale_ty_5be9e4_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Link to customer record (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('TRANSFER', 'Bank Transfer'), ('CREDIT', 'Credit (Pay Later)')], default='CASH', max_length=20),
        ),
        migrations.RemoveField(
            model_name='order',
            name='credit_approved_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='credit_due_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sale_type',
        ),
    ]
