# Generated by Django 6.0.1 on 2026-03-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_orderpayment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='credit_due_date',
            field=models.DateField(blank=True, db_index=True, help_text='Due date for credit payment', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='credit_terms_days',
            field=models.IntegerField(blank=True, help_text='Payment due in X days (for credit sales)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sale_type',
            field=models.CharField(choices=[('CASH', 'Cash Sale'), ('CREDIT', 'Credit Sale')], db_index=True, default='CASH', help_text='Sale type determines payment terms', max_length=10),
        ),
    ]
