# Generated by Django 6.0.1 on 2026-04-01 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_alter_customer_customer_type_salesperson_and_more'),
        ('orders', '0012_order_credit_due_date_order_credit_terms_days_and_more'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-completed_at', '-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_status_079368_idx',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-completed_at'], name='orders_orde_complet_4806d6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-completed_at'], name='orders_orde_status_c34625_idx'),
        ),
    ]
