# Generated by Django 6.0.1 on 2026-02-04 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registers', to='sales.store')),
            ],
        ),
        migrations.CreateModel(
            name='CashierSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashier_sessions', to=settings.AUTH_USER_MODEL)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='sales.register')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='sales.store')),
            ],
        ),
        migrations.AddIndex(
            model_name='register',
            index=models.Index(fields=['store', 'is_active'], name='sales_regis_store_i_6145fe_idx'),
        ),
        migrations.AddIndex(
            model_name='cashiersession',
            index=models.Index(fields=['store', 'register', 'opened_at'], name='sales_cashi_store_i_b371cc_idx'),
        ),
        migrations.AddIndex(
            model_name='cashiersession',
            index=models.Index(fields=['cashier', 'opened_at'], name='sales_cashi_cashier_a04f07_idx'),
        ),
        migrations.AddIndex(
            model_name='cashiersession',
            index=models.Index(fields=['register', 'closed_at'], name='sales_cashi_registe_03c361_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashiersession',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_at__isnull', True)), fields=('register',), name='uniq_open_session_per_register'),
        ),
    ]
