# Generated by Django 6.0.1 on 2026-02-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_city_customer_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address_line',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
