# Generated by Django 6.0.1 on 2026-03-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(blank=True, db_index=True, help_text='Format: CUST-YYYYMMDD-NNNN', max_length=50, null=True, unique=True),
        ),
    ]
