# Generated by Django 6.0.1 on 2026-03-06 11:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customer_customer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum credit allowed', max_digits=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('SUSPENDED', 'Suspended'), ('BLOCKED', 'Blocked')], default='APPROVED', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_terms_days',
            field=models.IntegerField(default=30, help_text='Default payment terms in days'),
        ),
    ]
