# Generated by Django 6.0.1 on 2026-03-30 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_customer_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('RETAILER', 'Retailer'), ('DISTRIBUTOR', 'Distributor')], db_index=True, default='INDIVIDUAL', max_length=20),
        ),
        migrations.CreateModel(
            name='SalesPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=17, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('employee_id', models.CharField(blank=True, help_text='Employee / staff ID', max_length=50, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, help_text='Link to system user account (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_person_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Person',
                'verbose_name_plural': 'Sales People',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='sales_person',
            field=models.ForeignKey(blank=True, help_text='Sales representative assigned to this customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.salesperson'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_type'], name='customers_c_custome_47da94_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['sales_person'], name='customers_c_sales_p_751dea_idx'),
        ),
    ]
