# Generated by Django 6.0.1 on 2026-04-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_alter_customer_customer_type_salesperson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('RETAILER', 'Retailer'), ('DISTRIBUTOR', 'Distributor')], db_index=True, default='INDIVIDUAL', max_length=20),
        ),
    ]
