# Generated by Django 6.0.1 on 2026-02-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='print_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
