# Generated by Django 6.0.1 on 2026-02-04 09:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('ADJ', 'Adjustment'), ('SALE', 'Sale'), ('RESTOCK', 'Restock'), ('DAMAGE', 'Damage/Loss'), ('RETURN', 'Return')], max_length=10)),
                ('quantity', models.IntegerField(help_text='Positive = increase, Negative = decrease')),
                ('stock_before', models.IntegerField()),
                ('stock_after', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('reason', models.CharField(blank=True, choices=[('damaged', 'Damaged'), ('expired', 'Expired'), ('lost', 'Lost/Theft'), ('recount', 'Stock Recount'), ('correction', 'Correction'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['variant', '-created_at'], name='inventory_s_variant_608d8a_idx'), models.Index(fields=['movement_type', '-created_at'], name='inventory_s_movemen_a71f62_idx')],
            },
        ),
    ]
