# Generated by Django 6.0.1 on 2026-02-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='reference_type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('ORDER', 'Sale Order'), ('ORDER_CANCEL', 'Order Cancellation'), ('ADJUSTMENT', 'Manual Adjustment'), ('RETURN', 'Customer Return'), ('DAMAGE', 'Damage/Loss'), ('TRANSFER', 'Transfer')], default=1, help_text='Type of transaction', max_length=20),
            preserve_default=False,
        ),
    ]
