# Generated by Django 6.0.1 on 2026-02-27 16:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0003_stockmovement_created_by_stockmovement_reference_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingStockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease')], max_length=10)),
                ('quantity', models.IntegerField(help_text='Amount to adjust', validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_change', models.IntegerField(help_text='Calculated change (positive or negative)')),
                ('reason', models.CharField(choices=[('damaged', 'Damaged'), ('expired', 'Expired'), ('lost', 'Lost/Theft'), ('recount', 'Stock Recount'), ('correction', 'Correction'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('stock_at_request', models.IntegerField()),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustment_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_adjustments', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', '-requested_at'], name='inventory_p_status_73ff4e_idx'), models.Index(fields=['variant', 'status'], name='inventory_p_variant_b8b678_idx')],
            },
        ),
    ]
