# Generated by Django 6.0.1 on 2026-03-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_pendingstockadjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingstockadjustment',
            name='reason',
            field=models.CharField(choices=[('newstock', 'New Stock'), ('correction', 'Correction'), ('expired', 'Expired'), ('damaged', 'Damaged'), ('lost', 'Lost/Theft'), ('other', 'Other')], max_length=20),
        ),
    ]
