# Generated by Django 6.0.1 on 2026-03-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_pendingstockadjustment_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingstockadjustment',
            name='reason',
            field=models.CharField(choices=[('restock', 'New Stock'), ('correction', 'Correction'), ('expired', 'Expired'), ('damaged', 'Damaged'), ('lost', 'Lost/Theft'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('ADJ', 'Adjustment'), ('SALE', 'Sale'), ('RESTOCK', 'Restock'), ('CORRECTION', 'Correction'), ('DAMAGE', 'Damage/Loss'), ('RETURN', 'Return')], max_length=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(blank=True, choices=[('restock', 'New Stock'), ('correction', 'Correction'), ('expired', 'Expired'), ('damaged', 'Damaged'), ('lost', 'Lost/Theft'), ('other', 'Other')], max_length=20),
        ),
    ]
