# Generated by Django 6.0.1 on 2026-03-06 11:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0009_customer_credit_limit_customer_credit_status_and_more'),
        ('orders', '0012_order_credit_due_date_order_credit_terms_days_and_more'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_id', models.CharField(db_index=True, help_text='Unique ledger identifier', max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('SALE', 'Credit Sale'), ('PAYMENT', 'Payment Received'), ('ADJUSTMENT', 'Balance Adjustment'), ('WRITEOFF', 'Bad Debt Write-off'), ('REFUND', 'Refund Issued')], default='SALE', max_length=20)),
                ('transaction_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total credit amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total paid so far', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('balance_outstanding', models.DecimalField(decimal_places=2, help_text='Remaining balance', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid in Full'), ('OVERDUE', 'Overdue'), ('WRITTEN_OFF', 'Written Off')], db_index=True, default='PENDING', max_length=20)),
                ('due_date', models.DateField(blank=True, db_index=True, help_text='Payment due date', null=True)),
                ('terms_days', models.IntegerField(default=30, help_text='Payment terms in days')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_ledgers_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer who owes money', on_delete=django.db.models.deletion.PROTECT, related_name='credit_ledger_entries', to='customers.customer')),
                ('order', models.OneToOneField(blank=True, help_text='Related order for credit sale', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_ledger', to='orders.order')),
            ],
            options={
                'verbose_name': 'Credit Ledger Entry',
                'verbose_name_plural': 'Credit Ledger Entries',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(db_index=True, help_text='Unique payment identifier', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('MOBILE_MONEY', 'Mobile Money')], default='CASH', max_length=20)),
                ('payment_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction reference', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('cashier_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_payments', to='sales.cashiersession')),
                ('customer', models.ForeignKey(help_text='Customer making payment', on_delete=django.db.models.deletion.PROTECT, related_name='credit_payments', to='customers.customer')),
                ('ledger', models.ForeignKey(help_text='Credit ledger entry this payment is for', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='credit.creditledger')),
                ('received_by', models.ForeignKey(help_text='Staff who received payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Payment',
                'verbose_name_plural': 'Credit Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='creditledger',
            index=models.Index(fields=['customer', '-transaction_date'], name='credit_cred_custome_cfc0a4_idx'),
        ),
        migrations.AddIndex(
            model_name='creditledger',
            index=models.Index(fields=['status', 'due_date'], name='credit_cred_status_f99414_idx'),
        ),
        migrations.AddIndex(
            model_name='creditledger',
            index=models.Index(fields=['-transaction_date'], name='credit_cred_transac_bfedc3_idx'),
        ),
        migrations.AddIndex(
            model_name='creditledger',
            index=models.Index(fields=['ledger_id'], name='credit_cred_ledger__b1aa2c_idx'),
        ),
        migrations.AddIndex(
            model_name='creditpayment',
            index=models.Index(fields=['ledger', '-payment_date'], name='credit_cred_ledger__4a5d48_idx'),
        ),
        migrations.AddIndex(
            model_name='creditpayment',
            index=models.Index(fields=['customer', '-payment_date'], name='credit_cred_custome_dd034a_idx'),
        ),
        migrations.AddIndex(
            model_name='creditpayment',
            index=models.Index(fields=['-payment_date'], name='credit_cred_payment_a2e0b2_idx'),
        ),
    ]
