# Generated by Django 6.0.1 on 2026-03-09 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_productvariant_name'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInventoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True)),
                ('opening_stock', models.IntegerField(default=0, help_text='Stock at start of day')),
                ('stock_added', models.IntegerField(default=0, help_text='Stock added during day (production/purchase)')),
                ('stock_removed', models.IntegerField(default=0, help_text='Stock removed during day (wastage/damage)')),
                ('quantity_sold', models.IntegerField(default=0, help_text='Quantity sold during day')),
                ('expected_closing', models.IntegerField(default=0, help_text='Expected stock at end of day')),
                ('actual_closing', models.IntegerField(default=0, help_text='Actual stock at end of day')),
                ('variance', models.IntegerField(default=0, help_text='Difference (shrinkage/overage)')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, help_text='Sales revenue for this item', max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_inventory_reports', to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_inventory_reports', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'daily_inventory_reports',
                'ordering': ['-report_date', 'product__name'],
                'indexes': [models.Index(fields=['-report_date'], name='daily_inven_report__6e35d3_idx'), models.Index(fields=['product', '-report_date'], name='daily_inven_product_d35cd5_idx'), models.Index(fields=['variant', '-report_date'], name='daily_inven_variant_361a72_idx')],
                'unique_together': {('report_date', 'product', 'variant')},
            },
        ),
    ]
