# Generated by Django 6.0.1 on 2026-03-09 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_dailyinventoryreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('file_format', models.CharField(max_length=10)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/')),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('row_count', models.IntegerField(default=0, help_text='Number of data rows')),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('filters_applied', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_emails', models.TextField(blank=True, help_text='Additional email addresses (comma-separated)')),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['next_run'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('DAILY_INVENTORY', 'Daily Inventory Report'), ('INVENTORY_MOVEMENT', 'Inventory Movement Report'), ('SALES_SUMMARY', 'Sales Summary Report'), ('CREDIT_AGING', 'Credit Aging Report'), ('CUSTOMER_ANALYSIS', 'Customer Analysis Report'), ('PRODUCT_PERFORMANCE', 'Product Performance Report'), ('CASHIER_PERFORMANCE', 'Cashier Performance Report'), ('PROFIT_LOSS', 'Profit & Loss Report'), ('LOW_STOCK_ALERT', 'Low Stock Alert Report'), ('OVERDUE_CREDIT', 'Overdue Credit Report')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('frequency', models.CharField(choices=[('MANUAL', 'Manual Only'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='MANUAL', max_length=20)),
                ('schedule_time', models.TimeField(blank=True, help_text='Time to generate report (for scheduled reports)', null=True)),
                ('default_format', models.CharField(choices=[('EXCEL', 'Excel'), ('PDF', 'PDF')], default='EXCEL', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='dailyinventoryreport',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='dailyinventoryreport',
            name='daily_inven_report__6e35d3_idx',
        ),
        migrations.RemoveIndex(
            model_name='dailyinventoryreport',
            name='daily_inven_product_d35cd5_idx',
        ),
        migrations.RemoveIndex(
            model_name='dailyinventoryreport',
            name='daily_inven_variant_361a72_idx',
        ),
        migrations.RemoveIndex(
            model_name='dailysalesreport',
            name='daily_sales_report__5dcc22_idx',
        ),
        migrations.AlterUniqueTogether(
            name='monthlysalesreport',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='monthlysalesreport',
            name='monthly_sal_year_0282d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='productperformancereport',
            name='product_per_period__b31028_idx',
        ),
        migrations.RemoveIndex(
            model_name='productperformancereport',
            name='product_per_product_bc5bf6_idx',
        ),
        migrations.DeleteModel(
            name='ProductPerformanceReport',
        ),
        migrations.AlterUniqueTogether(
            name='weeklysalesreport',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='weeklysalesreport',
            name='weekly_sale_year_999553_idx',
        ),
        migrations.RemoveIndex(
            model_name='yearlysalesreport',
            name='yearly_sale_year_9a6d42_idx',
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='recipients',
            field=models.ManyToManyField(help_text='Users who will receive the report', related_name='scheduled_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='report_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.reporttemplate'),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='report_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='reports.reporttemplate'),
        ),
        migrations.RemoveField(
            model_name='dailyinventoryreport',
            name='product',
        ),
        migrations.RemoveField(
            model_name='dailyinventoryreport',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='dailysalesreport',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='monthlysalesreport',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='weeklysalesreport',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='yearlysalesreport',
            name='generated_by',
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['-generated_at'], name='reports_gen_generat_646feb_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['report_template', '-generated_at'], name='reports_gen_report__dd7ce2_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['generated_by', '-generated_at'], name='reports_gen_generat_e2bb98_idx'),
        ),
        migrations.DeleteModel(
            name='DailyInventoryReport',
        ),
        migrations.DeleteModel(
            name='DailySalesReport',
        ),
        migrations.DeleteModel(
            name='MonthlySalesReport',
        ),
        migrations.DeleteModel(
            name='WeeklySalesReport',
        ),
        migrations.DeleteModel(
            name='YearlySalesReport',
        ),
    ]
