# Generated by Django 6.0.1 on 2026-03-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(blank=True, help_text='e.g 800g for weight, Big for size or Black for color', max_length=200),
        ),
    ]
