# Generated by Django 6.0.1 on 2026-03-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_productvariant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='distributor_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default price for Distributor customers at product level', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='retailer_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default price for Retailer customers at product level', max_digits=10),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='distributor_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price for Distributor customers. Falls back to product distributor_price if 0.', max_digits=10),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='retailer_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price for Retailer customers. Falls back to product retailer_price if 0.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Standard retail price (used when no variant price is set)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Standard (individual) price for this variant', max_digits=10),
        ),
    ]
